import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const bricolageGrotesque = localFont({
  src: '../public/fonts/BricolageGrotesque-font.ttf',
  variable: "--font-bricolage-groteque"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${bricolageGrotesque.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
